### ISSUE TITLE
Getting edition list with author fails due to different bio formats

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#10]
Example:

` ol.Work.get('OL3087688W').editions`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/olclient/openlibrary.py", line 124, in editions
    for ed in editions]
  File "/Library/Python/2.7/site-packages/olclient/openlibrary.py", line 288, in _ol_edition_json_to_book_args
    for author in data.pop('authors', [])]
  File "/Library/Python/2.7/site-packages/olclient/openlibrary.py", line 445, in get
    bio=data.pop('bio', {}).get('value', u''),
AttributeError: 'unicode' object has no attribute 'get'
```

The page in question is: https://openlibrary.org/works/OL3087688W/editions.json
1 edition with author field: 
"/authors/OL482817A"

Some authors have bios of format `"bio": "text"` while others have, and the client expects, the format:

`"bio":  {"type": "/type/text", "value": "Bio text"}` 

Not sure why there is a variation in the data, there seem to be lots of both styles.

**Comment by hornc** [comment]
This is now fixed, closing.
