### ISSUE TITLE
Command line first use, exception if credentials have not been configured

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#119]
Command line first use, exception if credentials have not been configured:

`ol`
=>
```
Traceback (most recent call last):
  File "/usr/local/bin/ol", line 9, in <module>
    load_entry_point('openlibrary-client==0.0.18', 'console_scripts', 'ol')()
  File "/usr/local/lib/python2.7/dist-packages/olclient/cli.py", line 91, in main
    ol = OpenLibrary()
  File "/usr/local/lib/python2.7/dist-packages/olclient/openlibrary.py", line 64, in __init__
    self.login(credentials)
  File "/usr/local/lib/python2.7/dist-packages/olclient/openlibrary.py", line 88, in login
    raise ValueError("No cookie set")
ValueError: No cookie set
```

Should handle the exception and provide an informative message on 
`  --configure        Configure ol client with credentials`
/ show help

**Comment by rahul-kumi** [comment]
@hornc,
I have tried solving this case by including a try-except block.
The solution involves allowing the `ValueError` to be raised in the try block, which is immediately handled by the except block where a prompt asking the user to configure the credentials and the command usage is printed.
I wanted to get your view before raising a PR.
