### ISSUE TITLE
Unable to login to a OL account (on colab)

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary-client#322]
OS:Linux
No config file existed before
I tried to login with `ia --configure`, but the login fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/ol", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/olclient/cli.py", line 84, in main
    ia.configure(email, password)
  File "/usr/local/lib/python3.7/dist-packages/internetarchive/api.py", line 548, in configure
    host,
  File "/usr/local/lib/python3.7/dist-packages/internetarchive/config.py", line 44, in get_auth_config
    r = requests.post(u, params=p, data=d)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:///services/xauthn/': No host supplied
```

**Comment by jimman2003** [comment]
After some thought,this seems to me like the host in that url is missing entirely...

**Comment by cclauss** [comment]
Or it is just `/`

**Comment by JeneeW** [comment]
Here is the function call that is passing an empty string for the host: https://github.com/jjjake/internetarchive/blob/bd9aed72e0c11bf94dc8b004eb7524b7801f48ee/internetarchive/api.py#L545

It's an empty string due to the default parameter right above:
https://github.com/jjjake/internetarchive/blob/bd9aed72e0c11bf94dc8b004eb7524b7801f48ee/internetarchive/api.py#L531

Everything works if the default parameter is set to "archive.org".
